# Generated by Django 5.2.3 on 2025-07-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cnpj',
            field=models.CharField(blank=True, default=None, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_empresa',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Nome da Empresa'),
        ),
    ]
