# Generated by Django 4.2.23 on 2026-08-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_convite_convite_uq_convite_pendente_email_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='max_fundos',
            field=models.PositiveIntegerField(default=10, help_text='Número máximo de fundos que esta empresa pode cadastrar.'),
        ),
    ]
