# Generated by Django 4.2.23 on 2026-08-04 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_empresa_max_fundos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Token único para validação da redefinição (UUID4)', unique=True, verbose_name='Token')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('USED', 'Utilizado'), ('CANCELLED', 'Cancelado')], db_index=True, default='PENDING', help_text='Estado atual da solicitação', max_length=10, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do token', verbose_name='Criado em')),
                ('expira_em', models.DateTimeField(help_text='Data e hora de expiração do token', verbose_name='Expira em')),
                ('usado_em', models.DateTimeField(blank=True, help_text='Data e hora em que o token foi utilizado', null=True, verbose_name='Usado em')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Endereço IP de quem solicitou a redefinição', null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device de quem solicitou a redefinição', verbose_name='User Agent')),
                ('usuario', models.ForeignKey(help_text='Usuário que solicitou a redefinição de senha', on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Token de Redefinição de Senha',
                'verbose_name_plural': 'Tokens de Redefinição de Senha',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['usuario', 'status'], name='idx_pwdreset_usuario_status'), models.Index(fields=['token'], name='idx_pwdreset_token'), models.Index(fields=['status', 'expira_em'], name='idx_pwdreset_status_expira')],
            },
        ),
    ]
