# Generated by Django 5.2.3 on 2025-07-20 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapeamentoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta', models.CharField(max_length=30, unique=True)),
                ('grupo_df', models.CharField(max_length=255)),
                ('tipo', models.IntegerField(choices=[(1, 'Ativo'), (2, 'Passivo'), (3, 'Patrimônio Líquido'), (4, 'Resultado')])),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Mapeamento de CC',
                'verbose_name_plural': 'Mapeamentos de CC',
                'ordering': ['tipo', 'grupo_df', 'conta'],
            },
        ),
        migrations.CreateModel(
            name='Fundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fundo',
                'verbose_name_plural': 'Fundos',
                'ordering': ['usuario', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='BalanceteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('conta_corrente', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=255)),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='df.fundo')),
                ('tipo_conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='df.mapeamentocontas')),
            ],
            options={
                'verbose_name': 'Item do Balancete',
                'verbose_name_plural': 'Itens do Balancete',
                'ordering': ['conta_corrente'],
            },
        ),
    ]
