# Generated by Django 5.2.3 on 2025-07-21 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanceteitem',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='balanceteitem',
            name='tipo_conta',
        ),
        migrations.AlterField(
            model_name='balanceteitem',
            name='conta_corrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='df.mapeamentocontas'),
        ),
    ]
