# Generated by Django 5.2.3 on 2025-08-18 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('df', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundo',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa (tenant) proprietária deste fundo.', on_delete=django.db.models.deletion.CASCADE, related_name='fundos', to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='balanceteitem',
            name='fundo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balancete', to='df.fundo'),
        ),
        migrations.AddIndex(
            model_name='mapeamentocontas',
            index=models.Index(fields=['tipo', 'grupo_df'], name='idx_map_tipo_grupo'),
        ),
        migrations.AddField(
            model_name='balanceteitem',
            name='conta_corrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='df.mapeamentocontas'),
        ),
        migrations.AddIndex(
            model_name='fundo',
            index=models.Index(fields=['empresa', 'nome'], name='idx_fundo_emp_nome'),
        ),
        migrations.AddIndex(
            model_name='fundo',
            index=models.Index(fields=['empresa', 'cnpj'], name='idx_fundo_emp_cnpj'),
        ),
        migrations.AddConstraint(
            model_name='fundo',
            constraint=models.UniqueConstraint(fields=('empresa', 'cnpj'), name='uq_fundo_empresa_cnpj'),
        ),
        migrations.AddConstraint(
            model_name='fundo',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='uq_fundo_empresa_nome'),
        ),
        migrations.AddIndex(
            model_name='balanceteitem',
            index=models.Index(fields=['ano'], name='idx_bal_ano'),
        ),
        migrations.AddIndex(
            model_name='balanceteitem',
            index=models.Index(fields=['fundo', 'ano'], name='idx_bal_fundo_ano'),
        ),
        migrations.AddConstraint(
            model_name='balanceteitem',
            constraint=models.UniqueConstraint(fields=('fundo', 'ano', 'conta_corrente'), name='uq_balancete_fundo_ano_conta'),
        ),
    ]
