# Generated by Django 4.2.23 on 2025-08-25 22:40

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MecItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_posicao', models.DateField(db_index=True)),
                ('aplicacao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('resgate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('estorno', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('pl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('qtd_cotas', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('cota', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mec_itens', to='df.fundo')),
            ],
            options={
                'verbose_name': 'Item MEC',
                'verbose_name_plural': 'Itens MEC',
                'ordering': ['fundo', 'data_posicao'],
                'indexes': [models.Index(fields=['data_posicao'], name='idx_mecitem_data'), models.Index(fields=['fundo', 'data_posicao'], name='idx_mecitem_fundo_data')],
            },
        ),
        migrations.AddConstraint(
            model_name='mecitem',
            constraint=models.UniqueConstraint(fields=('fundo', 'data_posicao'), name='uq_mecitem_fundo_data'),
        ),
        migrations.AddConstraint(
            model_name='mecitem',
            constraint=models.CheckConstraint(check=models.Q(('aplicacao__gte', 0), ('resgate__gte', 0), ('estorno__gte', 0)), name='ck_mecitem_valores_nao_negativos'),
        ),
        migrations.AddConstraint(
            model_name='mecitem',
            constraint=models.CheckConstraint(check=models.Q(('pl__gte', 0), ('qtd_cotas__gte', 0), ('cota__gte', 0)), name='ck_mecitem_posicoes_nao_negativas'),
        ),
    ]
