# Generated by Django 4.2.23 on 2025-09-03 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0003_mecitem_mecitem_uq_mecitem_fundo_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoGrande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Grupão de Contas',
                'verbose_name_plural': 'Grupões de Contas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='GrupoPequeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.IntegerField(choices=[(1, 'Ativo'), (2, 'Passivo'), (3, 'Patrimônio Líquido'), (4, 'Resultado')])),
            ],
            options={
                'verbose_name': 'Grupinho de Contas',
                'verbose_name_plural': 'Grupinhos de Contas',
                'ordering': ['grupao', 'nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='mapeamentocontas',
            options={'ordering': ['grupo_pequeno', 'conta'], 'verbose_name': 'Mapeamento de CC', 'verbose_name_plural': 'Mapeamentos de CC'},
        ),
        migrations.RemoveIndex(
            model_name='mapeamentocontas',
            name='idx_map_tipo_grupo',
        ),
        migrations.RemoveField(
            model_name='mapeamentocontas',
            name='grupo_df',
        ),
        migrations.RemoveField(
            model_name='mapeamentocontas',
            name='tipo',
        ),
        migrations.AddField(
            model_name='grupopequeno',
            name='grupao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupinhos', to='df.grupogrande'),
        ),
        migrations.AddField(
            model_name='mapeamentocontas',
            name='grupo_pequeno',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas', to='df.grupopequeno'),
        ),
    ]
