# Generated by Django 4.2.23 on 2025-09-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0004_grupogrande_grupopequeno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupogrande',
            name='ordem',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
