# Generated by Django 4.2.23 on 2025-10-02 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0005_grupogrande_ordem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupopequeno',
            name='tipo',
        ),
        migrations.AddField(
            model_name='grupogrande',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Ativo'), (2, 'Passivo'), (3, 'Patrimônio Líquido'), (4, 'Resultado')], null=True),
        ),
        migrations.AlterField(
            model_name='mapeamentocontas',
            name='grupo_pequeno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas', to='df.grupopequeno'),
        ),
        migrations.AddConstraint(
            model_name='grupogrande',
            constraint=models.UniqueConstraint(fields=('nome', 'tipo'), name='uq_grupogrande_nome_tipo'),
        ),
        migrations.AddConstraint(
            model_name='grupopequeno',
            constraint=models.UniqueConstraint(fields=('nome', 'grupao'), name='uq_grupopequeno_nome_grupao'),
        ),
    ]
