# Generated by Django 4.2.23 on 2025-11-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0006_remove_grupopequeno_tipo_grupogrande_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceteitem',
            name='data_referencia',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
