# Generated by Django 4.2.23 on 2025-11-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0007_balanceteitem_data_referencia'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='balanceteitem',
            name='uq_balancete_fundo_ano_conta',
        ),
        migrations.RemoveIndex(
            model_name='balanceteitem',
            name='idx_bal_ano',
        ),
        migrations.RemoveIndex(
            model_name='balanceteitem',
            name='idx_bal_fundo_ano',
        ),
        migrations.RemoveField(
            model_name='balanceteitem',
            name='ano',
        ),
        migrations.AddIndex(
            model_name='balanceteitem',
            index=models.Index(fields=['data_referencia'], name='idx_bal_data_referencia'),
        ),
        migrations.AddIndex(
            model_name='balanceteitem',
            index=models.Index(fields=['fundo', 'data_referencia'], name='idx_bal_fundo_data_referencia'),
        ),
        migrations.AddConstraint(
            model_name='balanceteitem',
            constraint=models.UniqueConstraint(fields=('fundo', 'data_referencia', 'conta_corrente'), name='uq_balancete_fundo_data_conta'),
        ),
    ]
